In [113]:
import pandas as pd
import numpy as np
from rake_nltk import Rake
import nltk
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity
nltk.download('stopwords')



[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Burak\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [114]:
#reading data
tags_df = pd.read_csv('../../Dataset/ml-latest-small/tags.csv')


In [115]:
tags_df.drop(columns=['userId','timestamp'], axis=1, inplace=True)
tags_df

movieId               tag
0       60756             funny
1       60756   Highly quotable
2       60756      will ferrell
3       89774      Boxing story
4       89774               MMA
...       ...               ...
3678     7382         for katie
3679     7936           austere
3680     3265            gun fu
3681     3265  heroic bloodshed
3682   168248  Heroic Bloodshed

[3683 rows x 2 columns]

In [116]:
#Unique number of movies
tags_df['movieId'].nunique() 

1572

In [117]:
tags_df['tag'] = tags_df['tag'].str.replace('[^ws]','') #to remove punctuations

In [118]:
tags_df['tag'] = tags_df['tag'].str.lower() #to lower every letter
tags_df['tag'] = tags_df['tag'].str.replace(' ','') #to remove all spaces
tags_df

movieId              tag
0       60756            funny
1       60756   highlyquotable
2       60756      willferrell
3       89774      boxingstory
4       89774              mma
...       ...              ...
3678     7382         forkatie
3679     7936          austere
3680     3265            gunfu
3681     3265  heroicbloodshed
3682   168248  heroicbloodshed

[3683 rows x 2 columns]

In [ ]:
cv = CountVectorizer()
count_matrix = cv.fit_transform(tags_df['tag'])
cosine_sim = cosine_similarity(count_matrix)

In [ ]:
print(cosine_sim)

[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 1.]
 [0. 0. 0. ... 0. 1. 1.]]
